---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    Controversial/CamelCaseClassName:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
  - "src/library/ThreemaGateway/threema-msgapi-sdk-php/**"
