---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
        Controversial/CamelCaseClassName:
            enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
  - "src/library/ThreemaGateway/threema-msgapi-sdk-php/**"
